name: Prueba

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "eeee"
      - name: touch File
        run: touch file.txt
      - name: write text
        run: echo "Prueba 1" >> file.txt
      - name: Read File
        run: cat file.txt

  others:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Prueba
        run: echo "hola"
